# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'admin.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStackedWidget, QTableWidget,
    QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(0, 42))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.pushButton_menu = QPushButton(self.frame_2)
        self.pushButton_menu.setObjectName(u"pushButton_menu")
        self.pushButton_menu.setGeometry(QRect(40, 10, 141, 41))
        font = QFont()
        font.setPointSize(12)
        self.pushButton_menu.setFont(font)
        self.label_4 = QLabel(self.frame_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(350, 10, 291, 31))
        font1 = QFont()
        font1.setPointSize(15)
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"background-color:rgb(170, 170, 255);")
        self.label_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.frame_2)

        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frame_4 = QFrame(self.frame_3)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setMinimumSize(QSize(200, 0))
        self.frame_4.setMaximumSize(QSize(0, 16777215))
        self.frame_4.setStyleSheet(u"QFrame{\n"
"background-color: rgb(170, 170, 255)\n"
"}\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"}\n"
"QPushButton:hover{\n"
"background-color:white;\n"
"}")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.pushButton_spisok = QPushButton(self.frame_4)
        self.pushButton_spisok.setObjectName(u"pushButton_spisok")
        self.pushButton_spisok.setGeometry(QRect(30, 80, 141, 41))
        self.pushButton_spisok.setMinimumSize(QSize(0, 40))
        font2 = QFont()
        font2.setPointSize(10)
        self.pushButton_spisok.setFont(font2)
        self.pushButton_korzina = QPushButton(self.frame_4)
        self.pushButton_korzina.setObjectName(u"pushButton_korzina")
        self.pushButton_korzina.setGeometry(QRect(30, 160, 141, 41))
        self.pushButton_korzina.setMinimumSize(QSize(0, 40))
        self.pushButton_korzina.setFont(font2)
        self.pushButton_zakazi = QPushButton(self.frame_4)
        self.pushButton_zakazi.setObjectName(u"pushButton_zakazi")
        self.pushButton_zakazi.setGeometry(QRect(30, 240, 141, 41))
        self.pushButton_zakazi.setMinimumSize(QSize(0, 40))
        self.pushButton_zakazi.setFont(font2)
        self.pushButton_2 = QPushButton(self.frame_4)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 320, 141, 41))
        self.pushButton_2.setFont(font2)

        self.horizontalLayout.addWidget(self.frame_4)

        self.frame_5 = QFrame(self.frame_3)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.stackedWidget = QStackedWidget(self.frame_5)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setFont(font)
        self.page_table = QWidget()
        self.page_table.setObjectName(u"page_table")
        self.tableWidget = QTableWidget(self.page_table)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 80, 501, 341))
        self.tableWidget.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"")
        self.label = QLabel(self.page_table)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 141, 41))
        font3 = QFont()
        font3.setBold(False)
        font3.setItalic(False)
        self.label.setFont(font3)
        self.label.setAlignment(Qt.AlignCenter)
        self.pushButton_obnovi = QPushButton(self.page_table)
        self.pushButton_obnovi.setObjectName(u"pushButton_obnovi")
        self.pushButton_obnovi.setGeometry(QRect(410, 440, 111, 31))
        font4 = QFont()
        font4.setBold(True)
        self.pushButton_obnovi.setFont(font4)
        self.comboBox = QComboBox(self.page_table)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(190, 20, 241, 41))
        self.comboBox.setContextMenuPolicy(Qt.NoContextMenu)
        self.comboBox.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.pushButton = QPushButton(self.page_table)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(50, 440, 111, 31))
        self.pushButton.setFont(font4)
        self.stackedWidget.addWidget(self.page_table)
        self.page_delete = QWidget()
        self.page_delete.setObjectName(u"page_delete")
        self.label_2 = QLabel(self.page_delete)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 70, 171, 31))
        self.label_2.setAlignment(Qt.AlignCenter)
        self.lineEdit = QLineEdit(self.page_delete)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(200, 70, 221, 31))
        self.lineEdit.setStyleSheet(u"background-color:rgb(255, 255, 255);")
        self.pushButton_poisc = QPushButton(self.page_delete)
        self.pushButton_poisc.setObjectName(u"pushButton_poisc")
        self.pushButton_poisc.setGeometry(QRect(430, 70, 91, 31))
        self.pushButton_ophorm_zakaz = QPushButton(self.page_delete)
        self.pushButton_ophorm_zakaz.setObjectName(u"pushButton_ophorm_zakaz")
        self.pushButton_ophorm_zakaz.setGeometry(QRect(390, 390, 131, 51))
        self.tableWidget_2 = QTableWidget(self.page_delete)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(20, 120, 501, 231))
        self.label_5 = QLabel(self.page_delete)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(170, 10, 211, 31))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_delete)
        self.page_add = QWidget()
        self.page_add.setObjectName(u"page_add")
        self.pushButton_4 = QPushButton(self.page_add)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(140, 20, 241, 41))
        self.frame_6 = QFrame(self.page_add)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(70, 100, 401, 281))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.lineEdit_2 = QLineEdit(self.frame_6)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(180, 40, 181, 31))
        self.lineEdit_2.setStyleSheet(u"background-color:white;")
        self.lineEdit_3 = QLineEdit(self.frame_6)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(180, 90, 181, 31))
        self.lineEdit_3.setStyleSheet(u"background-color:white;")
        self.lineEdit_4 = QLineEdit(self.frame_6)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(180, 140, 181, 31))
        self.lineEdit_4.setStyleSheet(u"background-color:white;")
        self.lineEdit_5 = QLineEdit(self.frame_6)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(180, 190, 181, 31))
        self.lineEdit_5.setStyleSheet(u"background-color:white;")
        self.label_3 = QLabel(self.frame_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 40, 121, 31))
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.frame_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 140, 121, 31))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.frame_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(40, 90, 121, 31))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.frame_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 190, 121, 31))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.pushButton_add_book = QPushButton(self.page_add)
        self.pushButton_add_book.setObjectName(u"pushButton_add_book")
        self.pushButton_add_book.setGeometry(QRect(340, 400, 131, 51))
        self.stackedWidget.addWidget(self.page_add)

        self.verticalLayout_3.addWidget(self.stackedWidget)


        self.horizontalLayout.addWidget(self.frame_5)


        self.verticalLayout_2.addWidget(self.frame_3)

        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)

        self.verticalLayout.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_menu.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0415\u041d\u042e", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0410\u041a\u041a\u0410\u0423\u041d\u0422 \u0410\u0414\u041c\u0418\u041d\u0418\u0421\u0422\u0420\u0410\u0422\u041e\u0420\u0410", None))
        self.pushButton_spisok.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0430\u0431\u043b\u0438\u0446\u0430", None))
        self.pushButton_korzina.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u0442\u0440\u043e\u043a\u0443", None))
        self.pushButton_zakazi.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u0434\u0430\u043d\u043d\u044b\u0445", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0431\u0430\u0437\u0443 \u0434\u0430\u043d\u043d\u044b\u0445", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0430\u0431\u043b\u0438\u0446\u0430", None))
        self.pushButton_obnovi.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0411\u041d\u041e\u0412\u0418\u0422\u042c", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"book", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"author", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"city", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"client", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"book_buy", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"\u0432\u0441\u0435 \u0442\u0430\u0431\u043b\u0438\u0446\u044b", None))

        self.comboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0442\u0430\u0431\u043b\u0438\u0446\u0443", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0414\u0410\u041b\u0418\u0422\u042c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0412\u0415\u0414\u0418\u0422\u0415 \u041d\u0410\u0417\u0412\u0410\u041d\u0418\u0415:", None))
        self.pushButton_poisc.setText(QCoreApplication.translate("MainWindow", u"\u041f\u041e\u0418\u0421\u041a", None))
        self.pushButton_ophorm_zakaz.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u0442\u0440\u043e\u0447\u043a\u0443", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0414\u0410\u041b\u0418\u0422\u042c \u0421\u0422\u0420\u041e\u041a\u0423", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\u0414\u041e\u0411\u0410\u0412\u041b\u0415\u041d\u0418\u0415 \u041d\u041e\u0412\u042b\u0425 \u0414\u0410\u041d\u041d\u042b\u0425", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"name_author", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"price", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"title", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"amount", None))
        self.pushButton_add_book.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a\u043d\u0438\u0433\u0443", None))
    # retranslateUi

